parameters:
    black_box_code.pando.content_bundle.controller.default_controller.class: BlackBoxCode\Pando\ContentBundle\Controller\DefaultController
    black_box_code.pando.content_bundle.service.block_variable_service.class: BlackBoxCode\Pando\ContentBundle\Service\BlockVariableService
    black_box_code.pando.content_bundle.service.dynamic_block_service.class: BlackBoxCode\Pando\ContentBundle\Service\DynamicBlockService
    black_box_code.pando.content_bundle.service.form_service.class: BlackBoxCode\Pando\ContentBundle\Service\FormService
    black_box_code.pando.content_bundle.service.form_container_service.class: BlackBoxCode\Pando\ContentBundle\Service\FormContainerService
    black_box_code.pando.content_bundle.service.method_service.class: BlackBoxCode\Pando\ContentBundle\Service\MethodService
    black_box_code.pando.content_bundle.twig.loader.phpcr_loader.class: BlackBoxCode\Pando\ContentBundle\Twig\Loader\PhpcrLoader
services:
    cmf_content.controller:
        class: "%black_box_code.pando.content_bundle.controller.default_controller.class%"
        arguments: ["@templating", "%cmf_content.default_template%", "@fos_rest.view_handler"]
        calls:
            - ['setFormservice', ["@black_box_code.pando.content_bundle.service.form_service"]]
            - ['setKernel', ["@http_kernel"]]
            - ['setRequestStack', ["@request_stack"]]
            - ['setDynamicRouter', ["@cmf_routing.dynamic_router"]]
    black_box_code.pando.content_bundle.service.form_service:
        class: "%black_box_code.pando.content_bundle.service.form_service.class%"
        calls:
            - ['setMethodservice', ["@black_box_code.pando.content_bundle.service.method_service"]]
            - ['setFormContainerservice', ["@black_box_code.pando.content_bundle.service.form_container_service"]]
            - ['setRequestStack', ["@request_stack"]]
            - ['setFormFactory', ["@form.factory"]]
    black_box_code.pando.content_bundle.service.method_service:
        class: "%black_box_code.pando.content_bundle.service.method_service.class%"
        calls:
            - ['setContainer', ["@service_container"]]
    black_box_code.pando.content_bundle.service.form_container_service:
        class: "%black_box_code.pando.content_bundle.service.form_container_service.class%"
    black_box_code.pando.content_bundle.service.dynamic_block_service:
        class: "%black_box_code.pando.content_bundle.service.dynamic_block_service.class%"
        calls:
            - ['setTemplating', ["@templating"]]
            - ['setBlockVariableservice', ["@black_box_code.pando.content_bundle.service.block_variable_service"]]
            - ['setFormservice', ["@black_box_code.pando.content_bundle.service.form_service"]]
            - ['setFormContainerservice', ["@black_box_code.pando.content_bundle.service.form_container_service"]]
        tags:
            - { name: 'sonata.block' }
    black_box_code.pando.content_bundle.service.block_variable_service:
        class: "%black_box_code.pando.content_bundle.service.block_variable_service.class%"
        calls:
            - ['setMethodservice', ["@black_box_code.pando.content_bundle.service.method_service"]]
            - ['setLogger', ["@logger"]]
    black_box_code.pando.content_bundle.twig.loader.phpcr_loader:
         class: "%black_box_code.pando.content_bundle.twig.loader.phpcr_loader.class%"
         calls:
             - ['setDocumentManager', ["@doctrine_phpcr.odm.document_manager"]]
         tags:
             - { name: twig.loader }