parameters:
    BlackBoxCode.Pando.ContentBundle.Controller.DefaultController.class: BlackBoxCode\Pando\ContentBundle\Controller\DefaultController
    BlackBoxCode.Pando.ContentBundle.Service.BlockVariableService.class: BlackBoxCode\Pando\ContentBundle\Service\BlockVariableService
    BlackBoxCode.Pando.ContentBundle.Service.DynamicBlockService.class: BlackBoxCode\Pando\ContentBundle\Service\DynamicBlockService
    BlackBoxCode.Pando.ContentBundle.Service.FormService.class: BlackBoxCode\Pando\ContentBundle\Service\FormService
    BlackBoxCode.Pando.ContentBundle.Service.FormContainerService.class: BlackBoxCode\Pando\ContentBundle\Service\FormContainerService
    BlackBoxCode.Pando.ContentBundle.Service.MethodService.class: BlackBoxCode\Pando\ContentBundle\Service\MethodService
services:
    cmf_content.controller:
        class: "%BlackBoxCode.Pando.ContentBundle.Controller.DefaultController.class%"
        arguments: ["@templating", "%cmf_content.default_template%", "@fos_rest.view_handler"]
        calls:
            - ['setFormService', ["@BlackBoxCode.Pando.ContentBundle.Service.FormService"]]
            - ['setKernel', ["@http_kernel"]]
            - ['setRequestStack', ["@request_stack"]]
            - ['setDynamicRouter', ["@cmf_routing.dynamic_router"]]
    BlackBoxCode.Pando.ContentBundle.Service.FormService:
        class: "%BlackBoxCode.Pando.ContentBundle.Service.FormService.class%"
        calls:
            - ['setMethodService', ["@BlackBoxCode.Pando.ContentBundle.Service.MethodService"]]
            - ['setFormContainerService', ["@BlackBoxCode.Pando.ContentBundle.Service.FormContainerService"]]
            - ['setRequestStack', ["@request_stack"]]
            - ['setFormFactory', ["@form.factory"]]
    BlackBoxCode.Pando.ContentBundle.Service.MethodService:
        class: "%BlackBoxCode.Pando.ContentBundle.Service.MethodService.class%"
        calls:
            - ['setContainer', ["@service_container"]]
    BlackBoxCode.Pando.ContentBundle.Service.FormContainerService:
        class: "%BlackBoxCode.Pando.ContentBundle.Service.FormContainerService.class%"
    BlackBoxCode.Pando.ContentBundle.Service.DynamicBlockService:
        class: "%BlackBoxCode.Pando.ContentBundle.Service.DynamicBlockService.class%"
        calls:
            - ['setTemplating', ["@templating"]]
            - ['setBlockVariableService', ["@BlackBoxCode.Pando.ContentBundle.Service.BlockVariableService"]]
            - ['setFormService', ["@BlackBoxCode.Pando.ContentBundle.Service.FormService"]]
            - ['setFormContainerService', ["@BlackBoxCode.Pando.ContentBundle.Service.FormContainerService"]]
    BlackBoxCode.Pando.ContentBundle.Service.BlockVariableService:
        class: "%BlackBoxCode.Pando.ContentBundle.Service.BlockVariableService.class%"
        calls:
            - ['setMethodService', ["@BlackBoxCode.Pando.ContentBundle.Service.MethodService"]]
