parameters:
    pando_content_bundle.service.method.class: BlackBoxCode\Pando\Bundle\ContentBundle\Service\MethodService

services:
    pando_content_bundle.method_service:
        class: "%pando_content_bundle.service.method.class%"
        calls:
            - ['setContainer', [@service_container]]